---
language: node_js
node_js:
  - "4"

sudo: false

cache:
  directories:
<<<<<<< HEAD
    - $HOME/.npm
    - $HOME/.cache # includes bowers cache
=======
    - node_modules
>>>>>>> cf43bb3632a93ad9637dd52428161c35fa73dd0f

before_install:
  - npm config set spin false
  - npm install -g bower
<<<<<<< HEAD
  - bower --version
  - npm install phantomjs-prebuilt
  - node_modules/phantomjs-prebuilt/bin/phantomjs --version
=======
  - npm install phantomjs-prebuilt
>>>>>>> cf43bb3632a93ad9637dd52428161c35fa73dd0f

install:
  - npm install
  - bower install

script:
  - npm test
